# Generated by Django 4.2.5 on 2023-11-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0019_remove_maindetails_map_url_contact_map_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='map_url',
        ),
        migrations.AddField(
            model_name='maindetails',
            name='map_url',
            field=models.TextField(blank=True, null=True, verbose_name='xerite'),
        ),
    ]
