# Generated by Django 4.2.7 on 2024-02-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0020_remove_contact_map_url_maindetails_map_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodel',
            name='description_az',
            field=models.TextField(null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='description_en',
            field=models.TextField(null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='text'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='sub_title_az',
            field=models.CharField(max_length=255, null=True, verbose_name='sub title'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='sub_title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='sub title'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='sub_title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='sub title'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='title_az',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='blog',
            name='description_az',
            field=models.TextField(null=True, verbose_name='movzu'),
        ),
        migrations.AddField(
            model_name='blog',
            name='description_en',
            field=models.TextField(null=True, verbose_name='movzu'),
        ),
        migrations.AddField(
            model_name='blog',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='movzu'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_az',
            field=models.CharField(max_length=255, null=True, verbose_name='basliq'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='basliq'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='basliq'),
        ),
        migrations.AddField(
            model_name='quota',
            name='name_az',
            field=models.CharField(max_length=255, null=True, verbose_name='ad'),
        ),
        migrations.AddField(
            model_name='quota',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='ad'),
        ),
        migrations.AddField(
            model_name='quota',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='ad'),
        ),
        migrations.AddField(
            model_name='quota',
            name='service_az',
            field=models.CharField(max_length=255, null=True, verbose_name='xidmetler'),
        ),
        migrations.AddField(
            model_name='quota',
            name='service_en',
            field=models.CharField(max_length=255, null=True, verbose_name='xidmetler'),
        ),
        migrations.AddField(
            model_name='quota',
            name='service_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='xidmetler'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_az',
            field=models.TextField(null=True, verbose_name='movzu'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(null=True, verbose_name='movzu'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='movzu'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_az',
            field=models.CharField(max_length=255, null=True, verbose_name='xidmet adi'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='xidmet adi'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='xidmet adi'),
        ),
        migrations.AddField(
            model_name='team',
            name='name_az',
            field=models.CharField(max_length=255, null=True, verbose_name='ad'),
        ),
        migrations.AddField(
            model_name='team',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='ad'),
        ),
        migrations.AddField(
            model_name='team',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='ad'),
        ),
        migrations.AddField(
            model_name='team',
            name='position_az',
            field=models.CharField(max_length=255, null=True, verbose_name='vezifesi'),
        ),
        migrations.AddField(
            model_name='team',
            name='position_en',
            field=models.CharField(max_length=255, null=True, verbose_name='vezifesi'),
        ),
        migrations.AddField(
            model_name='team',
            name='position_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='vezifesi'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='description_az',
            field=models.TextField(null=True, verbose_name='metn'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='description_en',
            field=models.TextField(null=True, verbose_name='metn'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='metn'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='profesion_az',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ixtisas'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='profesion_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ixtisas'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='profesion_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ixtisas'),
        ),
    ]
